export const FETCH_RECIPY_DATA   = 'FETCH_RECIPY_DATA';

export const FETCH_RECIPY_BEGIN   = 'FETCH_RECIPY_BEGIN';
export const FETCH_RECIPY_SUCCESS = 'FETCH_RECIPY_SUCCESS';
export const FETCH_RECIPY_FAILURE = 'FETCH_RECIPY_FAILURE';

export const RATING_STATE_UPDATE = 'RATING_STATE_UPDATE';
export const SEARCH_TEXT_UPDATE = 'SEARCH_TEXT_UPDATE'
export const FAVORITE_RECIPY_DATA = 'FAVORITE_RECIPY_DATA'
export const FAVORITE_DATA_UPDATE = 'FAVORITE_DATA_UPDATE'

//multi filter start
export const MULTI_ALL_SELECT_DATA = 'MULTI_ALL_SELECT_DATA';
export const MULTI_FILTER_DATA = 'MULTI_FILTER_DATA'
export const MULTI_LABEL_OPEN_DATA = 'MULTI_LABEL_OPEN_DATA'
export const MULTI_SELECT_DATA = 'MULTI_SELECT_DATA'